<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Errors;

use Clerk\Backend\Models\Components;
use Clerk\Backend\Utils;
/** ClerkErrors - Request was not successful */
class ClerkErrors
{
    /**
     * $errors
     *
     * @var array<\Clerk\Backend\Models\Components\ClerkError> $errors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\ClerkError>')]
    public array $errors;

    /**
     * $meta
     *
     * @var ?array<string, mixed> $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $meta = null;

    /**
     * @param  array<\Clerk\Backend\Models\Components\ClerkError>  $errors
     * @param  ?array<string, mixed>  $meta
     * @phpstan-pure
     */
    public function __construct(array $errors, ?array $meta = null)
    {
        $this->errors = $errors;
        $this->meta = $meta;
    }

    public function toException(): ClerkErrorsThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ClerkErrorsThrowable($message, (int) $code, $this);
    }
}