<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Errors;

class RevokeAdminPortalLinkTokenAdminPortalLinkTokensResponse404ResponseBodyThrowable extends \RuntimeException
{
    public RevokeAdminPortalLinkTokenAdminPortalLinkTokensResponse404ResponseBody $container;

    public function __construct(string $message, int $statusCode, RevokeAdminPortalLinkTokenAdminPortalLinkTokensResponse404ResponseBody $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}