<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Models\Components;
use Clerk\Backend\Utils\SpeakeasyMetadata;
class ApplyBillingSubscriptionItemDiscountRequest
{
    /**
     * The ID of the subscription item to apply the discount to
     *
     * @var string $subscriptionItemId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscription_item_id')]
    public string $subscriptionItemId;

    /**
     * Parameters for applying the discount
     *
     * @var \Clerk\Backend\Models\Components\ApplyCommerceDiscountRequest $applyCommerceDiscountRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\ApplyCommerceDiscountRequest $applyCommerceDiscountRequest;

    /**
     * @param  string  $subscriptionItemId
     * @param  \Clerk\Backend\Models\Components\ApplyCommerceDiscountRequest  $applyCommerceDiscountRequest
     * @phpstan-pure
     */
    public function __construct(string $subscriptionItemId, Components\ApplyCommerceDiscountRequest $applyCommerceDiscountRequest)
    {
        $this->subscriptionItemId = $subscriptionItemId;
        $this->applyCommerceDiscountRequest = $applyCommerceDiscountRequest;
    }
}