<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** CreateAdminPortalLinkTokenResponseBody - 201 Created */
class CreateAdminPortalLinkTokenResponseBody
{
    /**
     *
     * @var \Clerk\Backend\Models\Operations\CreateAdminPortalLinkTokenObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\CreateAdminPortalLinkTokenObject')]
    public CreateAdminPortalLinkTokenObject $object;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The origin-level admin_portal_link this token was issued for.
     *
     * @var string $adminPortalLinkId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('admin_portal_link_id')]
    public string $adminPortalLinkId;

    /**
     *
     * @var string $instanceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instance_id')]
    public string $instanceId;

    /**
     * The single-use admin portal link token. Returned only on creation. URL-borne; treat as a secret.
     *
     * @var string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    public string $token;

    /**
     *
     * @var bool $revoked
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revoked')]
    public bool $revoked;

    /**
     *
     * @var bool $expired
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expired')]
    public bool $expired;

    /**
     * The timestamp for when the token was created, in milliseconds.
     *
     * @var float $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public float $createdAt;

    /**
     * The timestamp for when the token was last updated, in milliseconds.
     *
     * @var float $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public float $updatedAt;

    /**
     * Optional. Present only when the link is scoped to an existing org.
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public ?string $organizationId;

    /**
     * Optional opaque reference to the IT contact associated with this link.
     *
     * @var ?string $itContactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('it_contact_id')]
    public ?string $itContactId;

    /**
     * Caller-provided scopes for this token.
     *
     * @var ?array<string> $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    public ?array $scopes;

    /**
     *
     * @var ?string $revocationReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revocation_reason')]
    public ?string $revocationReason;

    /**
     * The timestamp for when the token will expire, in milliseconds.
     *
     * @var ?float $expiration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiration')]
    public ?float $expiration;

    /**
     * @param  \Clerk\Backend\Models\Operations\CreateAdminPortalLinkTokenObject  $object
     * @param  string  $id
     * @param  string  $adminPortalLinkId
     * @param  string  $instanceId
     * @param  string  $token
     * @param  bool  $revoked
     * @param  bool  $expired
     * @param  float  $createdAt
     * @param  float  $updatedAt
     * @param  ?string  $organizationId
     * @param  ?string  $itContactId
     * @param  ?array<string>  $scopes
     * @param  ?string  $revocationReason
     * @param  ?float  $expiration
     * @phpstan-pure
     */
    public function __construct(CreateAdminPortalLinkTokenObject $object, string $id, string $adminPortalLinkId, string $instanceId, string $token, bool $revoked, bool $expired, float $createdAt, float $updatedAt, ?string $organizationId = null, ?string $itContactId = null, ?array $scopes = null, ?string $revocationReason = null, ?float $expiration = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->adminPortalLinkId = $adminPortalLinkId;
        $this->instanceId = $instanceId;
        $this->token = $token;
        $this->revoked = $revoked;
        $this->expired = $expired;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->organizationId = $organizationId;
        $this->itContactId = $itContactId;
        $this->scopes = $scopes;
        $this->revocationReason = $revocationReason;
        $this->expiration = $expiration;
    }
}