<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateEnterpriseConnectionRequestBody
{
    /**
     * The display name of the connection
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The identity provider (e.g. saml_custom, oidc_custom)
     *
     * @var Provider $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\Provider')]
    public Provider $provider;

    /**
     * Domains associated with the enterprise connection (required; at least one). Values are normalized to lowercase. Each domain must be a valid fully qualified domain name.
     *
     * @var array<string> $domains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domains')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $domains;

    /**
     * Custom attributes to map from the IdP to the user's profile via SSO or SCIM provisioning. Requires the custom attributes feature to be enabled for the instance.
     *
     * @var ?array<CustomAttributes> $customAttributes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_attributes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Operations\CustomAttributes>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customAttributes = null;

    /**
     * Organization ID when the connection is linked to an organization
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     * Whether the enterprise connection is active. When true, IdP metadata must be provided via the `saml` object.
     *
     * @var ?bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $active = null;

    /**
     * SAML connection-specific properties. Only applied when the enterprise connection uses SAML (e.g. provider is saml_custom).
     *
     * Use this to set IdP configuration, attribute mapping, and other SAML-specific settings at creation time.
     *
     * @var ?Saml $saml
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\Saml|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Saml $saml = null;

    /**
     * OIDC connection-specific properties. Only applied when the enterprise connection uses OIDC (e.g. provider is oidc_custom).
     *
     * @var ?Oidc $oidc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('oidc')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\Oidc|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Oidc $oidc = null;

    /**
     * @param  string  $name
     * @param  Provider  $provider
     * @param  array<string>  $domains
     * @param  ?array<CustomAttributes>  $customAttributes
     * @param  ?string  $organizationId
     * @param  ?bool  $active
     * @param  ?Saml  $saml
     * @param  ?Oidc  $oidc
     * @phpstan-pure
     */
    public function __construct(string $name, Provider $provider, array $domains, ?array $customAttributes = null, ?string $organizationId = null, ?bool $active = null, ?Saml $saml = null, ?Oidc $oidc = null)
    {
        $this->name = $name;
        $this->provider = $provider;
        $this->domains = $domains;
        $this->customAttributes = $customAttributes;
        $this->organizationId = $organizationId;
        $this->active = $active;
        $this->saml = $saml;
        $this->oidc = $oidc;
    }
}