<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateAdminPortalLinkTokenRequestBody
{
    /**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     *
     * @var ?string $itContactId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('it_contact_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $itContactId = null;

    /**
     * $scopes
     *
     * @var ?array<string> $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $scopes = null;

    /**
     *
     * @var ?int $secondsUntilExpiration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('seconds_until_expiration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $secondsUntilExpiration = null;

    /**
     * @param  ?string  $organizationId
     * @param  ?string  $itContactId
     * @param  ?array<string>  $scopes
     * @param  ?int  $secondsUntilExpiration
     * @phpstan-pure
     */
    public function __construct(?string $organizationId = null, ?string $itContactId = null, ?array $scopes = null, ?int $secondsUntilExpiration = 3600)
    {
        $this->organizationId = $organizationId;
        $this->itContactId = $itContactId;
        $this->scopes = $scopes;
        $this->secondsUntilExpiration = $secondsUntilExpiration;
    }
}