<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateSCIMGroupRoleMappingRequestBody
{
    /**
     * The SCIM group ID from the identity provider.
     *
     * @var string $scimGroupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_group_id')]
    public string $scimGroupId;

    /**
     * The ID of the organization role to assign to members of the SCIM group.
     *
     * @var string $roleId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role_id')]
    public string $roleId;

    /**
     * The precedence for this mapping. Lower values take priority when a user belongs
     *
     * to multiple mapped groups. If omitted, the mapping is appended with the
     * next-highest precedence.
     *
     * @var ?int $precedence
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('precedence')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $precedence = null;

    /**
     * @param  string  $scimGroupId
     * @param  string  $roleId
     * @param  ?int  $precedence
     * @phpstan-pure
     */
    public function __construct(string $scimGroupId, string $roleId, ?int $precedence = null)
    {
        $this->scimGroupId = $scimGroupId;
        $this->roleId = $roleId;
        $this->precedence = $precedence;
    }
}