<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateMachineTokenRequestBody
{
    /**
     * ID of the machine creating the token. Must be be prefixed with `mch_`. Must only contain lowercase letters, numbers, and underscores.
     *
     * @var string $machineId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('machine_id')]
    public string $machineId;

    /**
     * Claims to include in the JWT
     *
     * @var ?CreateMachineTokenClaims $claims
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('claims')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\CreateMachineTokenClaims|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateMachineTokenClaims $claims = null;

    /**
     * Token lifetime in seconds. Defaults to 30 seconds if not specified.
     *
     * @var ?int $expiresInSeconds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_in_seconds')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expiresInSeconds = null;

    /**
     * Allowed clock skew in seconds. Defaults to 5 seconds if not specified.
     *
     * @var ?int $allowedClockSkew
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowed_clock_skew')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $allowedClockSkew = null;

    /**
     * @param  string  $machineId
     * @param  ?CreateMachineTokenClaims  $claims
     * @param  ?int  $expiresInSeconds
     * @param  ?int  $allowedClockSkew
     * @phpstan-pure
     */
    public function __construct(string $machineId, ?CreateMachineTokenClaims $claims = null, ?int $expiresInSeconds = null, ?int $allowedClockSkew = 5)
    {
        $this->machineId = $machineId;
        $this->claims = $claims;
        $this->expiresInSeconds = $expiresInSeconds;
        $this->allowedClockSkew = $allowedClockSkew;
    }
}