<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


enum EnrollmentMode: string
{
    case ManualInvitation = 'manual_invitation';
    case AutomaticInvitation = 'automatic_invitation';
    case AutomaticSuggestion = 'automatic_suggestion';
    case EnterpriseSso = 'enterprise_sso';
    case MinusManualInvitation = '-manual_invitation';
    case MinusAutomaticInvitation = '-automatic_invitation';
    case MinusAutomaticSuggestion = '-automatic_suggestion';
    case MinusEnterpriseSso = '-enterprise_sso';
}
