<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/**
 * Controls the status of the replacement email address. Defaults to `verified`. Set to
 *
 * `reserved` to create it reserved (unverified but usable for sign-in and locked)
 * instead of verified.
 */
enum IdentificationStatus: string
{
    case Verified = 'verified';
    case Reserved = 'reserved';
}
