<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class InviteWaitlistEntryRequest
{
    /**
     * The ID of the waitlist entry to invite
     *
     * @var string $waitlistEntryId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=waitlist_entry_id')]
    public string $waitlistEntryId;

    /**
     *
     * @var ?\Clerk\Backend\Models\Operations\InviteWaitlistEntryRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?InviteWaitlistEntryRequestBody $requestBody = null;

    /**
     * @param  string  $waitlistEntryId
     * @param  ?\Clerk\Backend\Models\Operations\InviteWaitlistEntryRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $waitlistEntryId, ?InviteWaitlistEntryRequestBody $requestBody = null)
    {
        $this->waitlistEntryId = $waitlistEntryId;
        $this->requestBody = $requestBody;
    }
}