<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


enum ListEnterpriseConnectionTestRunsQueryParamStatus: string
{
    case Pending = 'pending';
    case Success = 'success';
    case Failed = 'failed';
}
