<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class ManagementDeleteApplicationRequest
{
    /**
     * Application ID.
     *
     * @var string $applicationID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=applicationID')]
    public string $applicationID;

    /**
     * Owner ID of the application (organization ID).
     *
     * @var string $ownerId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=owner_id')]
    public string $ownerId;

    /**
     * @param  string  $applicationID
     * @param  string  $ownerId
     * @phpstan-pure
     */
    public function __construct(string $applicationID, string $ownerId)
    {
        $this->applicationID = $applicationID;
        $this->ownerId = $ownerId;
    }
}