<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class Mappings
{
    /**
     * The SCIM group ID from the identity provider.
     *
     * @var string $scimGroupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_group_id')]
    public string $scimGroupId;

    /**
     * The ID of the organization role to assign to members of the SCIM group.
     *
     * @var string $roleId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role_id')]
    public string $roleId;

    /**
     * @param  string  $scimGroupId
     * @param  string  $roleId
     * @phpstan-pure
     */
    public function __construct(string $scimGroupId, string $roleId)
    {
        $this->scimGroupId = $scimGroupId;
        $this->roleId = $roleId;
    }
}