<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class RemoveUserPasswordRequestBody
{
    /**
     * Set to `true` to revoke all of the user's active sessions after removing the password.
     *
     * @var ?bool $signOutOfOtherSessions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sign_out_of_other_sessions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $signOutOfOtherSessions = null;

    /**
     * @param  ?bool  $signOutOfOtherSessions
     * @phpstan-pure
     */
    public function __construct(?bool $signOutOfOtherSessions = false)
    {
        $this->signOutOfOtherSessions = $signOutOfOtherSessions;
    }
}