<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class ReplaceUserEmailAddressRequestBody
{
    /**
     * The new email address. Must adhere to the RFC 5322 specification for email address format.
     *
     * @var string $emailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_address')]
    public string $emailAddress;

    /**
     * Controls the status of the replacement email address. Defaults to `verified`. Set to
     *
     * `reserved` to create it reserved (unverified but usable for sign-in and locked so no
     * other user can claim it), or to `unverified` to create it neither usable for sign-in
     * nor locked.
     *
     * **Warning:** `unverified` can lock the user out of their account. An unverified email
     * address cannot be used to sign in, so if the user has no other verified or reserved
     * identifier, they will be unable to authenticate and unable to verify this address.
     * Prefer `reserved` unless you specifically need the address left unclaimed — for
     * example so that another user can also hold it until one of them verifies it.
     *
     * @var ?\Clerk\Backend\Models\Operations\IdentificationStatus $identificationStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identification_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\IdentificationStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IdentificationStatus $identificationStatus = null;

    /**
     * If set to `true`, the user's previous primary email address is notified that the
     *
     * primary email address has changed. No notification is sent when the replacement
     * is the user's current primary email address. By default, no notification is sent.
     *
     * @var ?bool $notifyPrimaryEmailAddressChanged
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('notify_primary_email_address_changed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $notifyPrimaryEmailAddressChanged = null;

    /**
     * @param  string  $emailAddress
     * @param  ?\Clerk\Backend\Models\Operations\IdentificationStatus  $identificationStatus
     * @param  ?bool  $notifyPrimaryEmailAddressChanged
     * @phpstan-pure
     */
    public function __construct(string $emailAddress, ?IdentificationStatus $identificationStatus = IdentificationStatus::Verified, ?bool $notifyPrimaryEmailAddressChanged = false)
    {
        $this->emailAddress = $emailAddress;
        $this->identificationStatus = $identificationStatus;
        $this->notifyPrimaryEmailAddressChanged = $notifyPrimaryEmailAddressChanged;
    }
}