<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class ReplaceUserEmailAddressRequestBody
{
    /**
     * The new email address. Must adhere to the RFC 5322 specification for email address format.
     *
     * @var string $emailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_address')]
    public string $emailAddress;

    /**
     * Controls the status of the replacement email address. Defaults to `verified`. Set to
     *
     * `reserved` to create it reserved (unverified but usable for sign-in and locked)
     * instead of verified.
     *
     * @var ?\Clerk\Backend\Models\Operations\IdentificationStatus $identificationStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identification_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\IdentificationStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IdentificationStatus $identificationStatus = null;

    /**
     * @param  string  $emailAddress
     * @param  ?\Clerk\Backend\Models\Operations\IdentificationStatus  $identificationStatus
     * @phpstan-pure
     */
    public function __construct(string $emailAddress, ?IdentificationStatus $identificationStatus = IdentificationStatus::Verified)
    {
        $this->emailAddress = $emailAddress;
        $this->identificationStatus = $identificationStatus;
    }
}