<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class ReplaceDirectoryGroupRoleMappingsMappings
{
    /**
     * The ID of the organization role to assign to members of the group.
     *
     * @var string $roleId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role_id')]
    public string $roleId;

    /**
     * The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is required.
     *
     * @var ?string $directoryGroupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('directory_group_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $directoryGroupId = null;

    /**
     * The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both with different values is rejected.
     *
     * @var ?string $scimGroupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_group_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $scimGroupId = null;

    /**
     * @param  string  $roleId
     * @param  ?string  $directoryGroupId
     * @param  ?string  $scimGroupId
     * @phpstan-pure
     */
    public function __construct(string $roleId, ?string $directoryGroupId = null, ?string $scimGroupId = null)
    {
        $this->roleId = $roleId;
        $this->directoryGroupId = $directoryGroupId;
        $this->scimGroupId = $scimGroupId;
    }
}