<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class ReplaceUserPhoneNumberRequest
{
    /**
     * The ID of the user whose phone number to replace
     *
     * @var string $userId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=user_id')]
    public string $userId;

    /**
     *
     * @var \Clerk\Backend\Models\Operations\ReplaceUserPhoneNumberRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ReplaceUserPhoneNumberRequestBody $requestBody;

    /**
     * @param  string  $userId
     * @param  \Clerk\Backend\Models\Operations\ReplaceUserPhoneNumberRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $userId, ReplaceUserPhoneNumberRequestBody $requestBody)
    {
        $this->userId = $userId;
        $this->requestBody = $requestBody;
    }
}