<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class RevokeOAuthApplicationTokenRequestBody
{
    /**
     * The opaque OAuth access token or refresh token to revoke. All tokens associated with the same OAuth grant are also revoked.
     *
     * @var string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    public string $token;

    /**
     * @param  string  $token
     * @phpstan-pure
     */
    public function __construct(string $token)
    {
        $this->token = $token;
    }
}