<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class RevokeAdminPortalLinkTokenRequest
{
    /**
     *
     * @var string $adminPortalLinkTokenID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=adminPortalLinkTokenID')]
    public string $adminPortalLinkTokenID;

    /**
     *
     * @var \Clerk\Backend\Models\Operations\RevokeAdminPortalLinkTokenRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public RevokeAdminPortalLinkTokenRequestBody $requestBody;

    /**
     * @param  string  $adminPortalLinkTokenID
     * @param  \Clerk\Backend\Models\Operations\RevokeAdminPortalLinkTokenRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $adminPortalLinkTokenID, RevokeAdminPortalLinkTokenRequestBody $requestBody)
    {
        $this->adminPortalLinkTokenID = $adminPortalLinkTokenID;
        $this->requestBody = $requestBody;
    }
}