<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class RevokeUserTrustedDeviceRequest
{
    /**
     * The ID of the user that owns the trusted device
     *
     * @var string $userId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=user_id')]
    public string $userId;

    /**
     * The ID of the trusted device to revoke
     *
     * @var string $trustedDeviceId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=trusted_device_id')]
    public string $trustedDeviceId;

    /**
     * @param  string  $userId
     * @param  string  $trustedDeviceId
     * @phpstan-pure
     */
    public function __construct(string $userId, string $trustedDeviceId)
    {
        $this->userId = $userId;
        $this->trustedDeviceId = $trustedDeviceId;
    }
}