<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/**
 * Saml - SAML connection-specific properties. Only applied when the enterprise connection uses SAML (e.g. provider is saml_custom).
 *
 * Use this to set IdP configuration, attribute mapping, and other SAML-specific settings at creation time.
 */
class Saml
{
    /**
     * IdP entity ID
     *
     * @var ?string $idpEntityId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('idp_entity_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $idpEntityId = null;

    /**
     * IdP SSO URL
     *
     * @var ?string $idpSsoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('idp_sso_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $idpSsoUrl = null;

    /**
     * IdP certificate (PEM)
     *
     * @var ?string $idpCertificate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('idp_certificate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $idpCertificate = null;

    /**
     * URL to IdP metadata
     *
     * @var ?string $idpMetadataUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('idp_metadata_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $idpMetadataUrl = null;

    /**
     * Raw IdP metadata XML
     *
     * @var ?string $idpMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('idp_metadata')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $idpMetadata = null;

    /**
     * Attribute mapping for SAML attributes
     *
     * @var ?CreateEnterpriseConnectionAttributeMapping $attributeMapping
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attribute_mapping')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\CreateEnterpriseConnectionAttributeMapping|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateEnterpriseConnectionAttributeMapping $attributeMapping = null;

    /**
     *
     * @var ?bool $allowSubdomains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow_subdomains')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowSubdomains = null;

    /**
     *
     * @var ?bool $allowIdpInitiated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow_idp_initiated')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowIdpInitiated = null;

    /**
     *
     * @var ?bool $forceAuthn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('force_authn')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $forceAuthn = null;

    /**
     * @param  ?string  $idpEntityId
     * @param  ?string  $idpSsoUrl
     * @param  ?string  $idpCertificate
     * @param  ?string  $idpMetadataUrl
     * @param  ?string  $idpMetadata
     * @param  ?CreateEnterpriseConnectionAttributeMapping  $attributeMapping
     * @param  ?bool  $allowSubdomains
     * @param  ?bool  $allowIdpInitiated
     * @param  ?bool  $forceAuthn
     * @phpstan-pure
     */
    public function __construct(?string $idpEntityId = null, ?string $idpSsoUrl = null, ?string $idpCertificate = null, ?string $idpMetadataUrl = null, ?string $idpMetadata = null, ?CreateEnterpriseConnectionAttributeMapping $attributeMapping = null, ?bool $allowSubdomains = null, ?bool $allowIdpInitiated = null, ?bool $forceAuthn = null)
    {
        $this->idpEntityId = $idpEntityId;
        $this->idpSsoUrl = $idpSsoUrl;
        $this->idpCertificate = $idpCertificate;
        $this->idpMetadataUrl = $idpMetadataUrl;
        $this->idpMetadata = $idpMetadata;
        $this->attributeMapping = $attributeMapping;
        $this->allowSubdomains = $allowSubdomains;
        $this->allowIdpInitiated = $allowIdpInitiated;
        $this->forceAuthn = $forceAuthn;
    }
}