<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateOrganizationRequestBody
{
    /**
     * The new name of the organization.
     *
     * May not contain URLs or HTML.
     * Max length: 256
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The new slug of the organization, which needs to be unique in the instance
     *
     * @var ?string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $slug = null;

    /**
     * The maximum number of memberships allowed for this organization
     *
     * @var ?int $maxAllowedMemberships
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_allowed_memberships')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxAllowedMemberships = null;

    /**
     * If true, an admin can delete this organization with the Frontend API.
     *
     * @var ?bool $adminDeleteEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('admin_delete_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $adminDeleteEnabled = null;

    /**
     * Whether this organization can configure self-serve enterprise SSO.
     *
     * Requires the instance to have the self-serve SSO entitlement enabled.
     *
     * @var ?bool $selfServeSsoEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('self_serve_sso_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $selfServeSsoEnabled = null;

    /**
     * A custom date/time denoting _when_ the organization was created, specified in RFC3339 format (e.g. `2012-10-20T07:15:20.902Z`).
     *
     * @var ?string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $createdAt = null;

    /**
     * The key of the [role set](https://clerk.com/docs/guides/organizations/control-access/role-sets) to assign to this organization.
     *
     * @var ?string $roleSetKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role_set_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $roleSetKey = null;

    /**
     * Maps role keys in the organization's current role set to role keys in the new role set. Only applies when `role_set_key` changes the role set.
     *
     * Every role that a member holds and that the new role set does not include must be mapped, otherwise the request fails with a 422.
     * Mapping a role that both role sets include moves its members to the destination role.
     * Memberships are reassigned asynchronously after the response.
     *
     * @var ?array<string, string> $reassignmentMappings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reassignment_mappings')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $reassignmentMappings = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $slug
     * @param  ?int  $maxAllowedMemberships
     * @param  ?bool  $adminDeleteEnabled
     * @param  ?bool  $selfServeSsoEnabled
     * @param  ?string  $createdAt
     * @param  ?string  $roleSetKey
     * @param  ?array<string, string>  $reassignmentMappings
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $slug = null, ?int $maxAllowedMemberships = null, ?bool $adminDeleteEnabled = null, ?bool $selfServeSsoEnabled = null, ?string $createdAt = null, ?string $roleSetKey = null, ?array $reassignmentMappings = null)
    {
        $this->name = $name;
        $this->slug = $slug;
        $this->maxAllowedMemberships = $maxAllowedMemberships;
        $this->adminDeleteEnabled = $adminDeleteEnabled;
        $this->selfServeSsoEnabled = $selfServeSsoEnabled;
        $this->createdAt = $createdAt;
        $this->roleSetKey = $roleSetKey;
        $this->reassignmentMappings = $reassignmentMappings;
    }
}