<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateEnterpriseConnectionCustomAttributes
{
    /**
     * Display name for the custom attribute
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Key used to store the attribute in the user's metadata
     *
     * @var string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     * Path to extract the attribute value from SSO claims
     *
     * @var ?string $ssoPath
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sso_path')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ssoPath = null;

    /**
     * GJSON path to extract the attribute value from SCIM user resources
     *
     * @var ?string $scimPath
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_path')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $scimPath = null;

    /**
     * The new name for `scim_path`. Send either one, or both with the same value; sending both with different values is rejected.
     *
     * @var ?string $directoryPath
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('directory_path')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $directoryPath = null;

    /**
     * When true, the attribute supports multiple values; values from the IdP are written to public_metadata as an array. Defaults to false.
     *
     * @var ?bool $multiValued
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('multi_valued')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $multiValued = null;

    /**
     * @param  string  $name
     * @param  string  $key
     * @param  ?string  $ssoPath
     * @param  ?string  $scimPath
     * @param  ?string  $directoryPath
     * @param  ?bool  $multiValued
     * @phpstan-pure
     */
    public function __construct(string $name, string $key, ?string $ssoPath = null, ?string $scimPath = null, ?string $directoryPath = null, ?bool $multiValued = null)
    {
        $this->name = $name;
        $this->key = $key;
        $this->ssoPath = $ssoPath;
        $this->scimPath = $scimPath;
        $this->directoryPath = $directoryPath;
        $this->multiValued = $multiValued;
    }
}