<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateOAuthApplicationRequestBody
{
    /**
     * The new name of the OAuth application.
     *
     * Max length: 256
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * An array of redirect URIs of the new OAuth application
     *
     * @var ?array<string> $redirectUris
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redirect_uris')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $redirectUris = null;

    /**
     * The new callback URL of the OAuth application
     *
     * @var ?string $callbackUrl
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('callback_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $callbackUrl = null;

    /**
     * Replace the application's complete built-in and custom scope ceiling. Provide scope keys as a space-delimited string. Custom keys must exist in the instance OAuth scope catalog. Required built-in scopes, such as `offline_access`, must be included in the replacement set, otherwise the request is rejected. Omit this field to leave all scope assignments unchanged.
     *
     * @var ?string $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $scopes = null;

    /**
     * True to enable a consent screen to display in the authentication flow. This cannot be disabled for dynamically registered OAuth Applications.
     *
     * @var ?bool $consentScreenEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consent_screen_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $consentScreenEnabled = null;

    /**
     * True to require the Proof Key of Code Exchange (PKCE) flow.
     *
     * @var ?bool $pkceRequired
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pkce_required')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $pkceRequired = null;

    /**
     * True to enable the OAuth Device Authorization Grant for this application. Enabling requires the OAuth Device Authorization Grant feature to be enabled for the instance. Omit this field to leave the setting unchanged.
     *
     * @var ?bool $deviceAuthorizationGrantEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device_authorization_grant_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $deviceAuthorizationGrantEnabled = null;

    /**
     * If true, this client is public and you can use the Proof Key of Code Exchange (PKCE) flow.
     *
     * @var ?bool $public
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $public = null;

    /**
     * @param  ?string  $name
     * @param  ?array<string>  $redirectUris
     * @param  ?string  $callbackUrl
     * @param  ?string  $scopes
     * @param  ?bool  $consentScreenEnabled
     * @param  ?bool  $pkceRequired
     * @param  ?bool  $deviceAuthorizationGrantEnabled
     * @param  ?bool  $public
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?array $redirectUris = null, ?string $callbackUrl = null, ?string $scopes = null, ?bool $consentScreenEnabled = null, ?bool $pkceRequired = null, ?bool $deviceAuthorizationGrantEnabled = null, ?bool $public = null)
    {
        $this->name = $name;
        $this->redirectUris = $redirectUris;
        $this->callbackUrl = $callbackUrl;
        $this->scopes = $scopes;
        $this->consentScreenEnabled = $consentScreenEnabled;
        $this->pkceRequired = $pkceRequired;
        $this->deviceAuthorizationGrantEnabled = $deviceAuthorizationGrantEnabled;
        $this->public = $public;
    }
}