<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/** Controls the login_hint sent to the IdP on SSO sign-in */
enum UpdateEnterpriseConnectionMode: string
{
    case EmailAddress = 'email_address';
    case CustomAttribute = 'custom_attribute';
    case Off = 'off';
}
