<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateInstanceCommunicationRequestBody
{
    /**
     * ISO 3166-1 alpha-2 country codes to block for SMS delivery. Whole-list replacement. Codes must be uppercase, 2-letter, and unique within the array.
     *
     * @var ?array<string> $blockedCountryCodes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blocked_country_codes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $blockedCountryCodes = null;

    /**
     * @param  ?array<string>  $blockedCountryCodes
     * @phpstan-pure
     */
    public function __construct(?array $blockedCountryCodes = null)
    {
        $this->blockedCountryCodes = $blockedCountryCodes;
    }
}