<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateEnterpriseConnectionRequestBody
{
    /**
     * The display name of the enterprise connection
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Domains associated with the enterprise connection. Values are normalized to lowercase.
     *
     * Empty array means ignored (no change); non-empty array means set domains to the given list (replaces existing).
     *
     * @var ?array<string> $domains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domains')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $domains = null;

    /**
     * Whether the enterprise connection is active. When set to true (enabling), any existing verified organization domains for the same domain(s) will be removed so the connection can be enabled.
     *
     * @var ?bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $active = null;

    /**
     * Whether to sync user attributes on sign-in
     *
     * @var ?bool $syncUserAttributes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sync_user_attributes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $syncUserAttributes = null;

    /**
     * Whether to disable additional identifications
     *
     * @var ?bool $disableAdditionalIdentifications
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('disable_additional_identifications')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $disableAdditionalIdentifications = null;

    /**
     * Organization ID to link to this enterprise connection. Only linking is supported; sending this field sets or changes the linked organization. There is no way to unlink an organization once linked.
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     * SAML connection-specific properties. Only applied when the enterprise connection uses SAML.
     *
     * Use this to update IdP configuration, attribute mapping, and other SAML-specific settings.
     *
     * @var ?UpdateEnterpriseConnectionSaml $saml
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\UpdateEnterpriseConnectionSaml|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateEnterpriseConnectionSaml $saml = null;

    /**
     * OIDC connection-specific properties. Only applied when the enterprise connection uses OIDC.
     *
     * @var ?UpdateEnterpriseConnectionOidc $oidc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('oidc')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Operations\UpdateEnterpriseConnectionOidc|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateEnterpriseConnectionOidc $oidc = null;

    /**
     * @param  ?string  $name
     * @param  ?array<string>  $domains
     * @param  ?bool  $active
     * @param  ?bool  $syncUserAttributes
     * @param  ?bool  $disableAdditionalIdentifications
     * @param  ?string  $organizationId
     * @param  ?UpdateEnterpriseConnectionSaml  $saml
     * @param  ?UpdateEnterpriseConnectionOidc  $oidc
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?array $domains = null, ?bool $active = null, ?bool $syncUserAttributes = null, ?bool $disableAdditionalIdentifications = null, ?string $organizationId = null, ?UpdateEnterpriseConnectionSaml $saml = null, ?UpdateEnterpriseConnectionOidc $oidc = null)
    {
        $this->name = $name;
        $this->domains = $domains;
        $this->active = $active;
        $this->syncUserAttributes = $syncUserAttributes;
        $this->disableAdditionalIdentifications = $disableAdditionalIdentifications;
        $this->organizationId = $organizationId;
        $this->saml = $saml;
        $this->oidc = $oidc;
    }
}