<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class UpdateInstanceProtectRequestBody
{
    /**
     * Set true to enforce Protect rules on this instance. Set false to stop enforcing and return the instance to its default posture, where traffic is still evaluated in shadow but nothing is blocked. This does not remove the instance from Protect.
     *
     * @var ?bool $rulesEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rules_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $rulesEnabled = null;

    /**
     *
     * @var ?bool $specterEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('specter_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $specterEnabled = null;

    /**
     * @param  ?bool  $rulesEnabled
     * @param  ?bool  $specterEnabled
     * @phpstan-pure
     */
    public function __construct(?bool $rulesEnabled = null, ?bool $specterEnabled = null)
    {
        $this->rulesEnabled = $rulesEnabled;
        $this->specterEnabled = $specterEnabled;
    }
}