<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ApplyCommerceDiscountRequest
{
    /**
     * The ID of the discount to apply to the subscription item.
     *
     * @var string $discountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_id')]
    public string $discountId;

    /**
     * @param  string  $discountId
     * @phpstan-pure
     */
    public function __construct(string $discountId)
    {
        $this->discountId = $discountId;
    }
}