<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** BiometricCredentialList - Success */
class BiometricCredentialList
{
    /**
     * $data
     *
     * @var array<\Clerk\Backend\Models\Components\BiometricCredential> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\BiometricCredential>')]
    public array $data;

    /**
     * Total number of biometric credentials
     *
     * @var int $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    public int $totalCount;

    /**
     * @param  array<\Clerk\Backend\Models\Components\BiometricCredential>  $data
     * @param  int  $totalCount
     * @phpstan-pure
     */
    public function __construct(array $data, int $totalCount)
    {
        $this->data = $data;
        $this->totalCount = $totalCount;
    }
}