<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Cnames
{
    /**
     *
     * @var ?CNAMEStatus $accounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accounts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CNAMEStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CNAMEStatus $accounts = null;

    /**
     *
     * @var ?CNAMEStatus $clerk
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clerk')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CNAMEStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CNAMEStatus $clerk = null;

    /**
     *
     * @var ?CNAMEStatus $clkDomainkey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clk._domainkey')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CNAMEStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CNAMEStatus $clkDomainkey = null;

    /**
     *
     * @var ?CNAMEStatus $clk2Domainkey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clk2._domainkey')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CNAMEStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CNAMEStatus $clk2Domainkey = null;

    /**
     *
     * @var ?CNAMEStatus $clkmail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clkmail')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CNAMEStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CNAMEStatus $clkmail = null;

    /**
     * @param  ?CNAMEStatus  $accounts
     * @param  ?CNAMEStatus  $clerk
     * @param  ?CNAMEStatus  $clkDomainkey
     * @param  ?CNAMEStatus  $clk2Domainkey
     * @param  ?CNAMEStatus  $clkmail
     * @phpstan-pure
     */
    public function __construct(?CNAMEStatus $accounts = null, ?CNAMEStatus $clerk = null, ?CNAMEStatus $clkDomainkey = null, ?CNAMEStatus $clk2Domainkey = null, ?CNAMEStatus $clkmail = null)
    {
        $this->accounts = $accounts;
        $this->clerk = $clerk;
        $this->clkDomainkey = $clkDomainkey;
        $this->clk2Domainkey = $clk2Domainkey;
        $this->clkmail = $clkmail;
    }
}