<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class CommerceSubscriptionNextPaymentCredits
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\CommerceMoneyResponse $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceMoneyResponse')]
    public CommerceMoneyResponse $total;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\CommerceSubscriptionNextPaymentProration $proration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('proration')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionNextPaymentProration|null')]
    public ?CommerceSubscriptionNextPaymentProration $proration;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\CommerceSubscriptionNextPaymentPayer $payer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionNextPaymentPayer|null')]
    public ?CommerceSubscriptionNextPaymentPayer $payer;

    /**
     * @param  \Clerk\Backend\Models\Components\CommerceMoneyResponse  $total
     * @param  ?\Clerk\Backend\Models\Components\CommerceSubscriptionNextPaymentProration  $proration
     * @param  ?\Clerk\Backend\Models\Components\CommerceSubscriptionNextPaymentPayer  $payer
     * @phpstan-pure
     */
    public function __construct(CommerceMoneyResponse $total, ?CommerceSubscriptionNextPaymentProration $proration = null, ?CommerceSubscriptionNextPaymentPayer $payer = null)
    {
        $this->total = $total;
        $this->proration = $proration;
        $this->payer = $payer;
    }
}