<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** CommerceSubscription - A commerce subscription. */
class CommerceSubscription
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var CommerceSubscriptionObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionObject')]
    public CommerceSubscriptionObject $object;

    /**
     * Unique identifier for the commerce subscription.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The ID of the instance this subscription belongs to.
     *
     * @var string $instanceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instance_id')]
    public string $instanceId;

    /**
     * The current status of the subscription.
     *
     * @var CommerceSubscriptionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionStatus')]
    public CommerceSubscriptionStatus $status;

    /**
     * The ID of the payer for this subscription.
     *
     * @var string $payerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payer_id')]
    public string $payerId;

    /**
     * Unix timestamp (milliseconds) of creation.
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp (milliseconds) of last update.
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * Array of subscription items in this subscription.
     *
     * @var array<CommerceSubscriptionItem> $subscriptionItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\CommerceSubscriptionItem>')]
    public array $subscriptionItems;

    /**
     *
     * @var ?CommerceSubscriptionNextPayment $nextPayment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('next_payment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionNextPayment|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CommerceSubscriptionNextPayment $nextPayment = null;

    /**
     * Unix timestamp (milliseconds) when the subscription became active.
     *
     * @var ?int $activeAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $activeAt = null;

    /**
     * Unix timestamp (milliseconds) when the subscription became past due.
     *
     * @var ?int $pastDueAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('past_due_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $pastDueAt = null;

    /**
     * Whether the payer is eligible for a free trial.
     *
     * @var ?bool $eligibleForFreeTrial
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eligible_for_free_trial')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $eligibleForFreeTrial = null;

    /**
     * @param  CommerceSubscriptionObject  $object
     * @param  string  $id
     * @param  string  $instanceId
     * @param  CommerceSubscriptionStatus  $status
     * @param  string  $payerId
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  array<CommerceSubscriptionItem>  $subscriptionItems
     * @param  ?CommerceSubscriptionNextPayment  $nextPayment
     * @param  ?int  $activeAt
     * @param  ?int  $pastDueAt
     * @param  ?bool  $eligibleForFreeTrial
     * @phpstan-pure
     */
    public function __construct(CommerceSubscriptionObject $object, string $id, string $instanceId, CommerceSubscriptionStatus $status, string $payerId, int $createdAt, int $updatedAt, array $subscriptionItems, ?CommerceSubscriptionNextPayment $nextPayment = null, ?int $activeAt = null, ?int $pastDueAt = null, ?bool $eligibleForFreeTrial = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->instanceId = $instanceId;
        $this->status = $status;
        $this->payerId = $payerId;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->subscriptionItems = $subscriptionItems;
        $this->nextPayment = $nextPayment;
        $this->activeAt = $activeAt;
        $this->pastDueAt = $pastDueAt;
        $this->eligibleForFreeTrial = $eligibleForFreeTrial;
    }
}