<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** CommerceDiscountRedemptionResponse - A commerce discount redemption. */
class CommerceDiscountRedemptionResponse
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var \Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseObject')]
    public CommerceDiscountRedemptionResponseObject $object;

    /**
     * Unique identifier for the discount redemption.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Unique identifier for the subscription item the discount was applied to.
     *
     * @var string $subscriptionItemId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_item_id')]
    public string $subscriptionItemId;

    /**
     * Unique identifier for the discount that was applied.
     *
     * @var string $discountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_id')]
    public string $discountId;

    /**
     * How the discount was applied to the subscription item.
     *
     * @var \Clerk\Backend\Models\Components\Source $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Source')]
    public Source $source;

    /**
     * Number of billing cycles the discount has already been applied to.
     *
     * @var int $cyclesApplied
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cycles_applied')]
    public int $cyclesApplied;

    /**
     * Unix timestamp (in milliseconds) when the discount was redeemed.
     *
     * @var int $redeemedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redeemed_at')]
    public int $redeemedAt;

    /**
     * The display name of the discount.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The promo code used to redeem the discount, when applicable.
     *
     * @var ?string $promoCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('promo_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $promoCode = null;

    /**
     * The snapshotted discount effect.
     *
     * @var ?\Clerk\Backend\Models\Components\Effect $effect
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('effect')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Effect|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Effect $effect = null;

    /**
     * Remaining billing cycles the discount applies to. Null means the discount lasts forever.
     *
     * @var ?int $cyclesRemaining
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cycles_remaining')]
    public ?int $cyclesRemaining;

    /**
     * Current status of the discount redemption.
     *
     * @var ?\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CommerceDiscountRedemptionResponseStatus $status = null;

    /**
     * Identifier of the actor that redeemed the discount, when available.
     *
     * @var ?string $redeemedBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redeemed_by')]
    public ?string $redeemedBy;

    /**
     * Percent off when the effect is percentage.
     *
     * @var ?float $percentOff
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('percent_off')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $percentOff = null;

    /**
     * Fixed amount off when the effect is fixed_amount.
     *
     * @var ?\Clerk\Backend\Models\Components\AmountOff $amountOff
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_off')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\AmountOff|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AmountOff $amountOff = null;

    /**
     * How much this discount takes off the subscription item's next renewal charge.
     *
     * Present for either effect when next-payment data is available.
     *
     * @var ?\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CommerceDiscountRedemptionResponseAmount $amount = null;

    /**
     * @param  \Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseObject  $object
     * @param  string  $id
     * @param  string  $subscriptionItemId
     * @param  string  $discountId
     * @param  \Clerk\Backend\Models\Components\Source  $source
     * @param  int  $cyclesApplied
     * @param  int  $redeemedAt
     * @param  ?string  $name
     * @param  ?string  $promoCode
     * @param  ?\Clerk\Backend\Models\Components\Effect  $effect
     * @param  ?int  $cyclesRemaining
     * @param  ?\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseStatus  $status
     * @param  ?string  $redeemedBy
     * @param  ?float  $percentOff
     * @param  ?\Clerk\Backend\Models\Components\AmountOff  $amountOff
     * @param  ?\Clerk\Backend\Models\Components\CommerceDiscountRedemptionResponseAmount  $amount
     * @phpstan-pure
     */
    public function __construct(CommerceDiscountRedemptionResponseObject $object, string $id, string $subscriptionItemId, string $discountId, Source $source, int $cyclesApplied, int $redeemedAt, ?string $name = null, ?string $promoCode = null, ?Effect $effect = null, ?int $cyclesRemaining = null, ?CommerceDiscountRedemptionResponseStatus $status = null, ?string $redeemedBy = null, ?float $percentOff = null, ?AmountOff $amountOff = null, ?CommerceDiscountRedemptionResponseAmount $amount = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->subscriptionItemId = $subscriptionItemId;
        $this->discountId = $discountId;
        $this->source = $source;
        $this->cyclesApplied = $cyclesApplied;
        $this->redeemedAt = $redeemedAt;
        $this->name = $name;
        $this->promoCode = $promoCode;
        $this->effect = $effect;
        $this->cyclesRemaining = $cyclesRemaining;
        $this->status = $status;
        $this->redeemedBy = $redeemedBy;
        $this->percentOff = $percentOff;
        $this->amountOff = $amountOff;
        $this->amount = $amount;
    }
}