<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** String representing the object's type. */
enum DirectoryGroupRoleMappingDeletedObject: string
{
    case DirectoryGroupRoleMapping = 'directory_group_role_mapping';
}
