<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** DirectoryGroupRoleMappingList - A list of directory group role mappings, ordered by precedence. */
class DirectoryGroupRoleMappingList
{
    /**
     * $data
     *
     * @var array<\Clerk\Backend\Models\Components\DirectoryGroupRoleMapping> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\DirectoryGroupRoleMapping>')]
    public array $data;

    /**
     * Total number of directory group role mappings in the directory.
     *
     * @var int $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    public int $totalCount;

    /**
     * @param  array<\Clerk\Backend\Models\Components\DirectoryGroupRoleMapping>  $data
     * @param  int  $totalCount
     * @phpstan-pure
     */
    public function __construct(array $data, int $totalCount)
    {
        $this->data = $data;
        $this->totalCount = $totalCount;
    }
}