<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class EnterpriseConnectionTestRun
{
    /**
     * The test run ID
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The status of the test run
     *
     * @var \Clerk\Backend\Models\Components\EnterpriseConnectionTestRunStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\EnterpriseConnectionTestRunStatus')]
    public EnterpriseConnectionTestRunStatus $status;

    /**
     * The type of enterprise connection the test run was performed against
     *
     * @var \Clerk\Backend\Models\Components\ConnectionType $connectionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ConnectionType')]
    public ConnectionType $connectionType;

    /**
     * Unix timestamp in milliseconds when the test run was created
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Log entries captured during the test run
     *
     * @var ?array<\Clerk\Backend\Models\Components\Logs> $logs
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logs')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\Logs>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $logs = null;

    /**
     * The user information parsed from the IdP response
     *
     * @var ?\Clerk\Backend\Models\Components\ParsedUserInfo $parsedUserInfo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parsed_user_info')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ParsedUserInfo|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ParsedUserInfo $parsedUserInfo = null;

    /**
     * SAML-specific metadata, present for SAML connections
     *
     * @var ?\Clerk\Backend\Models\Components\Saml $saml
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Saml|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Saml $saml = null;

    /**
     * OAuth-specific metadata, present for OIDC connections
     *
     * @var ?\Clerk\Backend\Models\Components\Oauth $oauth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('oauth')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Oauth|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Oauth $oauth = null;

    /**
     * @param  string  $id
     * @param  \Clerk\Backend\Models\Components\EnterpriseConnectionTestRunStatus  $status
     * @param  \Clerk\Backend\Models\Components\ConnectionType  $connectionType
     * @param  int  $createdAt
     * @param  ?array<\Clerk\Backend\Models\Components\Logs>  $logs
     * @param  ?\Clerk\Backend\Models\Components\ParsedUserInfo  $parsedUserInfo
     * @param  ?\Clerk\Backend\Models\Components\Saml  $saml
     * @param  ?\Clerk\Backend\Models\Components\Oauth  $oauth
     * @phpstan-pure
     */
    public function __construct(string $id, EnterpriseConnectionTestRunStatus $status, ConnectionType $connectionType, int $createdAt, ?array $logs = null, ?ParsedUserInfo $parsedUserInfo = null, ?Saml $saml = null, ?Oauth $oauth = null)
    {
        $this->id = $id;
        $this->status = $status;
        $this->connectionType = $connectionType;
        $this->createdAt = $createdAt;
        $this->logs = $logs;
        $this->parsedUserInfo = $parsedUserInfo;
        $this->saml = $saml;
        $this->oauth = $oauth;
    }
}