<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** EnterpriseConnectionTestRuns - A list of enterprise connection test runs */
class EnterpriseConnectionTestRuns
{
    /**
     * $data
     *
     * @var array<\Clerk\Backend\Models\Components\EnterpriseConnectionTestRun> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\EnterpriseConnectionTestRun>')]
    public array $data;

    /**
     * Total number of test runs
     *
     * @var int $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    public int $totalCount;

    /**
     * @param  array<\Clerk\Backend\Models\Components\EnterpriseConnectionTestRun>  $data
     * @param  int  $totalCount
     * @phpstan-pure
     */
    public function __construct(array $data, int $totalCount)
    {
        $this->data = $data;
        $this->totalCount = $totalCount;
    }
}