<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** Instance - Success */
class Instance
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var \Clerk\Backend\Models\Components\InstanceObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\InstanceObject')]
    public InstanceObject $object;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $environmentType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('environment_type')]
    public string $environmentType;

    /**
     * $allowedOrigins
     *
     * @var ?array<string> $allowedOrigins
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowed_origins')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    public ?array $allowedOrigins;

    /**
     * The ID of the Clerk workspace that owns the instance's application. It is null when the application has no owner.
     *
     * @var ?string $workspaceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workspace_id')]
    public ?string $workspaceId;

    /**
     * @param  \Clerk\Backend\Models\Components\InstanceObject  $object
     * @param  string  $id
     * @param  string  $environmentType
     * @param  ?array<string>  $allowedOrigins
     * @param  ?string  $workspaceId
     * @phpstan-pure
     */
    public function __construct(InstanceObject $object, string $id, string $environmentType, ?array $allowedOrigins = null, ?string $workspaceId = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->environmentType = $environmentType;
        $this->allowedOrigins = $allowedOrigins;
        $this->workspaceId = $workspaceId;
    }
}