<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** InstanceRestrictions - Success */
class InstanceRestrictions
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     * @var InstanceRestrictionsObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\InstanceRestrictionsObject')]
    public InstanceRestrictionsObject $object;

    /**
     *
     * @var bool $allowlist
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowlist')]
    public bool $allowlist;

    /**
     *
     * @var bool $blocklist
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blocklist')]
    public bool $blocklist;

    /**
     *
     * @var bool $blockEmailSubaddresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('block_email_subaddresses')]
    public bool $blockEmailSubaddresses;

    /**
     *
     * @var bool $blockDisposableEmailDomains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('block_disposable_email_domains')]
    public bool $blockDisposableEmailDomains;

    /**
     *
     * @var bool $ignoreDotsForGmailAddresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ignore_dots_for_gmail_addresses')]
    public bool $ignoreDotsForGmailAddresses;

    /**
     * @param  InstanceRestrictionsObject  $object
     * @param  bool  $allowlist
     * @param  bool  $blocklist
     * @param  bool  $blockEmailSubaddresses
     * @param  bool  $blockDisposableEmailDomains
     * @param  bool  $ignoreDotsForGmailAddresses
     * @phpstan-pure
     */
    public function __construct(InstanceRestrictionsObject $object, bool $allowlist, bool $blocklist, bool $blockEmailSubaddresses, bool $blockDisposableEmailDomains, bool $ignoreDotsForGmailAddresses)
    {
        $this->object = $object;
        $this->allowlist = $allowlist;
        $this->blocklist = $blocklist;
        $this->blockEmailSubaddresses = $blockEmailSubaddresses;
        $this->blockDisposableEmailDomains = $blockDisposableEmailDomains;
        $this->ignoreDotsForGmailAddresses = $ignoreDotsForGmailAddresses;
    }
}