<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** The level used for the reverification */
enum Level: string
{
    case FirstFactor = 'first_factor';
    case SecondFactor = 'second_factor';
    case MultiFactor = 'multi_factor';
}
