<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ManagementCreateOrganizationRequest
{
    /**
     * The slug of the organization.
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     * The name of the organization.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The ID of the user who created the organization.
     *
     * @var ?string $createdBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_by')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $createdBy = null;

    /**
     * The maximum allowed memberships for the organization.
     *
     * @var ?int $maxAllowedMemberships
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_allowed_memberships')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxAllowedMemberships = null;

    /**
     * Public metadata for the organization.
     *
     * @var ?PublicMetadata $publicMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\PublicMetadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PublicMetadata $publicMetadata = null;

    /**
     * Private metadata for the organization.
     *
     * @var ?PrivateMetadata $privateMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('private_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\PrivateMetadata|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PrivateMetadata $privateMetadata = null;

    /**
     * The creation timestamp in RFC3339 format.
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * @param  string  $slug
     * @param  ?string  $name
     * @param  ?string  $createdBy
     * @param  ?int  $maxAllowedMemberships
     * @param  ?PublicMetadata  $publicMetadata
     * @param  ?PrivateMetadata  $privateMetadata
     * @param  ?\DateTime  $createdAt
     * @phpstan-pure
     */
    public function __construct(string $slug, ?string $name = null, ?string $createdBy = null, ?int $maxAllowedMemberships = null, ?PublicMetadata $publicMetadata = null, ?PrivateMetadata $privateMetadata = null, ?\DateTime $createdAt = null)
    {
        $this->slug = $slug;
        $this->name = $name;
        $this->createdBy = $createdBy;
        $this->maxAllowedMemberships = $maxAllowedMemberships;
        $this->publicMetadata = $publicMetadata;
        $this->privateMetadata = $privateMetadata;
        $this->createdAt = $createdAt;
    }
}