<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ManagementCreateApplicationRequest
{
    /**
     * The name of the application.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The owner ID (organization ID) of the application.
     *
     * @var string $ownerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('owner_id')]
    public string $ownerId;

    /**
     * The plan ID for the application (e.g., "free_2022_06", "pro_2023_11").
     *
     * @var string $planId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('plan_id')]
    public string $planId;

    /**
     * List of add-on IDs (e.g., ["enhanced_auth_2023_11", "enhanced_orgs_2023_11"]).
     *
     * @var ?array<string> $addonIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addon_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $addonIds = null;

    /**
     * The domain for the application (optional).
     *
     * @var ?string $domain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $domain = null;

    /**
     * Whether the application is paid externally.
     *
     * @var ?bool $paidExternally
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paid_externally')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $paidExternally = null;

    /**
     * Whether the application is in test mode.
     *
     * @var ?bool $testMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('test_mode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $testMode = null;

    /**
     * Maximum allowed users for the application.
     *
     * @var ?int $maxAllowedUsers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_allowed_users')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxAllowedUsers = null;

    /**
     * Maximum allowed organizations for the application.
     *
     * @var ?int $maxAllowedOrganizations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_allowed_organizations')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxAllowedOrganizations = null;

    /**
     * User settings for the application.
     *
     * @var ?UserSettings $userSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\UserSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UserSettings $userSettings = null;

    /**
     * Organization settings for the application.
     *
     * @var ?ManagementCreateApplicationRequestOrganizationSettings $organizationSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ManagementCreateApplicationRequestOrganizationSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ManagementCreateApplicationRequestOrganizationSettings $organizationSettings = null;

    /**
     * Session settings for the application.
     *
     * @var ?SessionSettings $sessionSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('session_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SessionSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SessionSettings $sessionSettings = null;

    /**
     * Native settings for the application.
     *
     * @var ?NativeSettings $nativeSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('native_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\NativeSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?NativeSettings $nativeSettings = null;

    /**
     * Experimental settings for the application.
     *
     * @var ?ExperimentalSettings $experimentalSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('experimental_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ExperimentalSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ExperimentalSettings $experimentalSettings = null;

    /**
     * Fraud settings for the application.
     *
     * @var ?FraudSettings $fraudSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fraud_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\FraudSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FraudSettings $fraudSettings = null;

    /**
     * Billing settings for the application.
     *
     * @var ?BillingSettings $billingSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\BillingSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingSettings $billingSettings = null;

    /**
     * Subscription metadata for the application.
     *
     * @var ?array<string, string> $subscriptionMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $subscriptionMetadata = null;

    /**
     * List of environment types to create instances for.
     *
     * @var ?array<EnvironmentTypes> $environmentTypes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('environment_types')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\EnvironmentTypes>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $environmentTypes = null;

    /**
     * @param  string  $name
     * @param  string  $ownerId
     * @param  string  $planId
     * @param  ?array<string>  $addonIds
     * @param  ?string  $domain
     * @param  ?bool  $paidExternally
     * @param  ?bool  $testMode
     * @param  ?int  $maxAllowedUsers
     * @param  ?int  $maxAllowedOrganizations
     * @param  ?UserSettings  $userSettings
     * @param  ?ManagementCreateApplicationRequestOrganizationSettings  $organizationSettings
     * @param  ?SessionSettings  $sessionSettings
     * @param  ?NativeSettings  $nativeSettings
     * @param  ?ExperimentalSettings  $experimentalSettings
     * @param  ?FraudSettings  $fraudSettings
     * @param  ?BillingSettings  $billingSettings
     * @param  ?array<string, string>  $subscriptionMetadata
     * @param  ?array<EnvironmentTypes>  $environmentTypes
     * @phpstan-pure
     */
    public function __construct(string $name, string $ownerId, string $planId, ?array $addonIds = null, ?string $domain = null, ?bool $paidExternally = null, ?bool $testMode = null, ?int $maxAllowedUsers = null, ?int $maxAllowedOrganizations = null, ?UserSettings $userSettings = null, ?ManagementCreateApplicationRequestOrganizationSettings $organizationSettings = null, ?SessionSettings $sessionSettings = null, ?NativeSettings $nativeSettings = null, ?ExperimentalSettings $experimentalSettings = null, ?FraudSettings $fraudSettings = null, ?BillingSettings $billingSettings = null, ?array $subscriptionMetadata = null, ?array $environmentTypes = null)
    {
        $this->name = $name;
        $this->ownerId = $ownerId;
        $this->planId = $planId;
        $this->addonIds = $addonIds;
        $this->domain = $domain;
        $this->paidExternally = $paidExternally;
        $this->testMode = $testMode;
        $this->maxAllowedUsers = $maxAllowedUsers;
        $this->maxAllowedOrganizations = $maxAllowedOrganizations;
        $this->userSettings = $userSettings;
        $this->organizationSettings = $organizationSettings;
        $this->sessionSettings = $sessionSettings;
        $this->nativeSettings = $nativeSettings;
        $this->experimentalSettings = $experimentalSettings;
        $this->fraudSettings = $fraudSettings;
        $this->billingSettings = $billingSettings;
        $this->subscriptionMetadata = $subscriptionMetadata;
        $this->environmentTypes = $environmentTypes;
    }
}