<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


enum ManagementDomainStatusResponseSslStatus: string
{
    case Complete = 'complete';
    case InProcess = 'in_process';
    case NotStarted = 'not_started';
    case Failed = 'failed';
    case Incomplete = 'incomplete';
}
