<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ManagementUpsertUserRequest
{
    /**
     * The email address of the user.
     *
     * @var string $emailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_address')]
    public string $emailAddress;

    /**
     * The first name of the user.
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    public string $firstName;

    /**
     * The last name of the user.
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    public string $lastName;

    /**
     * @param  string  $emailAddress
     * @param  string  $firstName
     * @param  string  $lastName
     * @phpstan-pure
     */
    public function __construct(string $emailAddress, string $firstName, string $lastName)
    {
        $this->emailAddress = $emailAddress;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
    }
}