<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class ManagementUpdateApplicationRequest
{
    /**
     * The name of the application.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The plan ID for the application.
     *
     * @var ?string $planId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('plan_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $planId = null;

    /**
     * List of add-on IDs for the application.
     *
     * @var ?array<string> $addonIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addon_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $addonIds = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $planId
     * @param  ?array<string>  $addonIds
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $planId = null, ?array $addonIds = null)
    {
        $this->name = $name;
        $this->planId = $planId;
        $this->addonIds = $addonIds;
    }
}