<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** NativeSettings - Native settings for the application. */
class NativeSettings
{

    public function __construct()
    {
    }
}