<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** NextInvoice - Information about the next invoice. */
class NextInvoice
{
    /**
     * Amount for the next payment.
     *
     * @var ?CommerceSubscriptionItemNextInvoiceAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionItemNextInvoiceAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CommerceSubscriptionItemNextInvoiceAmount $amount = null;

    /**
     * Unix timestamp (in milliseconds) for the next payment date.
     *
     * @var ?int $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $date = null;

    /**
     * @param  ?CommerceSubscriptionItemNextInvoiceAmount  $amount
     * @param  ?int  $date
     * @phpstan-pure
     */
    public function __construct(?CommerceSubscriptionItemNextInvoiceAmount $amount = null, ?int $date = null)
    {
        $this->amount = $amount;
        $this->date = $date;
    }
}