<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** NextPayment - Information about the next payment. */
class NextPayment
{
    /**
     * Amount for the next payment.
     *
     * @var ?CommerceSubscriptionItemNextPaymentAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceSubscriptionItemNextPaymentAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CommerceSubscriptionItemNextPaymentAmount $amount = null;

    /**
     * Unix timestamp (in milliseconds) for the next payment date.
     *
     * @var ?int $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $date = null;

    /**
     * @param  ?CommerceSubscriptionItemNextPaymentAmount  $amount
     * @param  ?int  $date
     * @phpstan-pure
     */
    public function __construct(?CommerceSubscriptionItemNextPaymentAmount $amount = null, ?int $date = null)
    {
        $this->amount = $amount;
        $this->date = $date;
    }
}