<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** OauthConfig - Present when the enterprise connection uses OIDC */
class OauthConfig
{
    /**
     * OAuth config ID
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Custom OIDC provider display name
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * OAuth provider key (e.g. oidc_custom)
     *
     * @var ?string $providerKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $providerKey = null;

    /**
     * Unix timestamp in milliseconds when the config was created
     *
     * @var ?int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $createdAt = null;

    /**
     * Unix timestamp in milliseconds when the config was last updated
     *
     * @var ?int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     * OAuth client ID
     *
     * @var ?string $clientId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientId = null;

    /**
     * OIDC discovery URL
     *
     * @var ?string $discoveryUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discovery_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $discoveryUrl = null;

    /**
     * Logo URL for the provider
     *
     * @var ?string $logoPublicUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logo_public_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $logoPublicUrl = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?string  $providerKey
     * @param  ?int  $createdAt
     * @param  ?int  $updatedAt
     * @param  ?string  $clientId
     * @param  ?string  $discoveryUrl
     * @param  ?string  $logoPublicUrl
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $name = null, ?string $providerKey = null, ?int $createdAt = null, ?int $updatedAt = null, ?string $clientId = null, ?string $discoveryUrl = null, ?string $logoPublicUrl = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->providerKey = $providerKey;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->clientId = $clientId;
        $this->discoveryUrl = $discoveryUrl;
        $this->logoPublicUrl = $logoPublicUrl;
    }
}