<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** SAMLConnectionLoginHint - Configuration for the login_hint sent to the IdP on SSO sign-in */
class SAMLConnectionLoginHint
{
    /**
     * Controls the login_hint sent to the IdP on SSO sign-in
     *
     * @var \Clerk\Backend\Models\Components\Mode $mode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Mode')]
    public Mode $mode;

    /**
     * The user public_metadata key whose value is sent as the login_hint when mode is custom_attribute
     *
     * @var ?string $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $source = null;

    /**
     * @param  \Clerk\Backend\Models\Components\Mode  $mode
     * @param  ?string  $source
     * @phpstan-pure
     */
    public function __construct(Mode $mode, ?string $source = null)
    {
        $this->mode = $mode;
        $this->source = $source;
    }
}