<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** Saml - SAML-specific metadata, present for SAML connections */
class Saml
{
    /**
     *
     * @var ?string $samlRequest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml_request')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $samlRequest = null;

    /**
     *
     * @var ?string $samlResponse
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml_response')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $samlResponse = null;

    /**
     *
     * @var ?string $relayState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('relay_state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $relayState = null;

    /**
     * @param  ?string  $samlRequest
     * @param  ?string  $samlResponse
     * @param  ?string  $relayState
     * @phpstan-pure
     */
    public function __construct(?string $samlRequest = null, ?string $samlResponse = null, ?string $relayState = null)
    {
        $this->samlRequest = $samlRequest;
        $this->samlResponse = $samlResponse;
        $this->relayState = $relayState;
    }
}