<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** SchemasCommerceSubscriptionItemNextPayment - Information about the next payment. */
class SchemasCommerceSubscriptionItemNextPayment
{
    /**
     * Per-unit total breakdown (for example, seats) for the next payment.
     *
     * @var ?array<\Clerk\Backend\Models\Components\CommercePerUnitTotal> $perUnitTotals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('per_unit_totals')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\CommercePerUnitTotal>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $perUnitTotals = null;

    /**
     * Base plan fee for the next payment. Does not include per-unit (e.g. seat) charges; see `totals.grand_total` for the full amount.
     *
     * @var ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SchemasCommerceSubscriptionItemNextPaymentAmount $amount = null;

    /**
     * Unix timestamp (in milliseconds) for the next payment date.
     *
     * @var ?int $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $date = null;

    /**
     * Breakdown of the recurring amount that will be billed at renewal (base fee + per-unit charges). Tax and credits are not previewed.
     *
     * @var ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentTotals $totals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totals')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentTotals|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SchemasCommerceSubscriptionItemNextPaymentTotals $totals = null;

    /**
     * @param  ?array<\Clerk\Backend\Models\Components\CommercePerUnitTotal>  $perUnitTotals
     * @param  ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentAmount  $amount
     * @param  ?int  $date
     * @param  ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentTotals  $totals
     * @phpstan-pure
     */
    public function __construct(?array $perUnitTotals = null, ?SchemasCommerceSubscriptionItemNextPaymentAmount $amount = null, ?int $date = null, ?SchemasCommerceSubscriptionItemNextPaymentTotals $totals = null)
    {
        $this->perUnitTotals = $perUnitTotals;
        $this->amount = $amount;
        $this->date = $date;
        $this->totals = $totals;
    }
}