<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class SchemasEnterpriseConnection
{
    /**
     * The enterprise connection ID
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The display name of the connection
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Whether the enterprise connection is active
     *
     * @var bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    public bool $active;

    /**
     * Domains associated with the enterprise connection
     *
     * @var array<string> $domains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domains')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $domains;

    /**
     * Unix timestamp in milliseconds when the connection was created
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp in milliseconds when the connection was last updated
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * Controls whether to update the user's attributes on each sign-in
     *
     * @var ?bool $syncUserAttributes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sync_user_attributes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $syncUserAttributes = null;

    /**
     * When true, users cannot add additional identifications when using this connection
     *
     * @var ?bool $disableAdditionalIdentifications
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('disable_additional_identifications')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $disableAdditionalIdentifications = null;

    /**
     * Whether this connection supports account linking via organization membership
     *
     * @var ?bool $allowOrganizationAccountLinking
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow_organization_account_linking')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowOrganizationAccountLinking = null;

    /**
     * Custom attributes to map from the IdP to the user's profile via SSO or SCIM provisioning
     *
     * @var ?array<CustomAttributes> $customAttributes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_attributes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\CustomAttributes>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $customAttributes = null;

    /**
     * Organization ID when the connection is linked to an organization
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     * Present when the enterprise connection uses SAML
     *
     * @var ?SchemasEnterpriseConnectionSamlConnection $samlConnection
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('saml_connection')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasEnterpriseConnectionSamlConnection|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SchemasEnterpriseConnectionSamlConnection $samlConnection = null;

    /**
     * Present when the enterprise connection uses OIDC
     *
     * @var ?OauthConfig $oauthConfig
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('oauth_config')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\OauthConfig|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OauthConfig $oauthConfig = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  bool  $active
     * @param  array<string>  $domains
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?bool  $syncUserAttributes
     * @param  ?bool  $disableAdditionalIdentifications
     * @param  ?bool  $allowOrganizationAccountLinking
     * @param  ?array<CustomAttributes>  $customAttributes
     * @param  ?string  $organizationId
     * @param  ?SchemasEnterpriseConnectionSamlConnection  $samlConnection
     * @param  ?OauthConfig  $oauthConfig
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, bool $active, array $domains, int $createdAt, int $updatedAt, ?bool $syncUserAttributes = null, ?bool $disableAdditionalIdentifications = null, ?bool $allowOrganizationAccountLinking = null, ?array $customAttributes = null, ?string $organizationId = null, ?SchemasEnterpriseConnectionSamlConnection $samlConnection = null, ?OauthConfig $oauthConfig = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->active = $active;
        $this->domains = $domains;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->syncUserAttributes = $syncUserAttributes;
        $this->disableAdditionalIdentifications = $disableAdditionalIdentifications;
        $this->allowOrganizationAccountLinking = $allowOrganizationAccountLinking;
        $this->customAttributes = $customAttributes;
        $this->organizationId = $organizationId;
        $this->samlConnection = $samlConnection;
        $this->oauthConfig = $oauthConfig;
    }
}