<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class SchemasCommerceSubscriptionItemNextPaymentCredits
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\CommerceMoneyResponse $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceMoneyResponse')]
    public CommerceMoneyResponse $total;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentProration $proration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('proration')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentProration|null')]
    public ?SchemasCommerceSubscriptionItemNextPaymentProration $proration;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentPayer $payer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentPayer|null')]
    public ?SchemasCommerceSubscriptionItemNextPaymentPayer $payer;

    /**
     * @param  \Clerk\Backend\Models\Components\CommerceMoneyResponse  $total
     * @param  ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentProration  $proration
     * @param  ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemNextPaymentPayer  $payer
     * @phpstan-pure
     */
    public function __construct(CommerceMoneyResponse $total, ?SchemasCommerceSubscriptionItemNextPaymentProration $proration = null, ?SchemasCommerceSubscriptionItemNextPaymentPayer $payer = null)
    {
        $this->total = $total;
        $this->proration = $proration;
        $this->payer = $payer;
    }
}