<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** SchemasCommerceSubscriptionItemTotals - Breakdown of the recurring amount that will be billed at renewal (base fee + per-unit charges). Tax and credits are not previewed. */
class SchemasCommerceSubscriptionItemTotals
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\CommerceMoneyResponse $subtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceMoneyResponse')]
    public CommerceMoneyResponse $subtotal;

    /**
     *
     * @var \Clerk\Backend\Models\Components\CommerceMoneyResponse $baseFee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('base_fee')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceMoneyResponse')]
    public CommerceMoneyResponse $baseFee;

    /**
     *
     * @var \Clerk\Backend\Models\Components\CommerceMoneyResponse $taxTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceMoneyResponse')]
    public CommerceMoneyResponse $taxTotal;

    /**
     *
     * @var \Clerk\Backend\Models\Components\CommerceMoneyResponse $grandTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('grand_total')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\CommerceMoneyResponse')]
    public CommerceMoneyResponse $grandTotal;

    /**
     * $perUnitTotals
     *
     * @var ?array<\Clerk\Backend\Models\Components\CommercePerUnitTotal> $perUnitTotals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('per_unit_totals')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\CommercePerUnitTotal>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $perUnitTotals = null;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemCredits $credits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('credits')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemCredits|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SchemasCommerceSubscriptionItemCredits $credits = null;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemDiscounts $discounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discounts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemDiscounts|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SchemasCommerceSubscriptionItemDiscounts $discounts = null;

    /**
     * @param  \Clerk\Backend\Models\Components\CommerceMoneyResponse  $subtotal
     * @param  \Clerk\Backend\Models\Components\CommerceMoneyResponse  $baseFee
     * @param  \Clerk\Backend\Models\Components\CommerceMoneyResponse  $taxTotal
     * @param  \Clerk\Backend\Models\Components\CommerceMoneyResponse  $grandTotal
     * @param  ?array<\Clerk\Backend\Models\Components\CommercePerUnitTotal>  $perUnitTotals
     * @param  ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemCredits  $credits
     * @param  ?\Clerk\Backend\Models\Components\SchemasCommerceSubscriptionItemDiscounts  $discounts
     * @phpstan-pure
     */
    public function __construct(CommerceMoneyResponse $subtotal, CommerceMoneyResponse $baseFee, CommerceMoneyResponse $taxTotal, CommerceMoneyResponse $grandTotal, ?array $perUnitTotals = null, ?SchemasCommerceSubscriptionItemCredits $credits = null, ?SchemasCommerceSubscriptionItemDiscounts $discounts = null)
    {
        $this->subtotal = $subtotal;
        $this->baseFee = $baseFee;
        $this->taxTotal = $taxTotal;
        $this->grandTotal = $grandTotal;
        $this->perUnitTotals = $perUnitTotals;
        $this->credits = $credits;
        $this->discounts = $discounts;
    }
}