<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** SCIMDirectoryList - A list of SCIM directories */
class SCIMDirectoryList
{
    /**
     * $data
     *
     * @var array<\Clerk\Backend\Models\Components\SCIMDirectory> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\SCIMDirectory>')]
    public array $data;

    /**
     * Total number of SCIM directories.
     *
     * @var int $totalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_count')]
    public int $totalCount;

    /**
     * @param  array<\Clerk\Backend\Models\Components\SCIMDirectory>  $data
     * @param  int  $totalCount
     * @phpstan-pure
     */
    public function __construct(array $data, int $totalCount)
    {
        $this->data = $data;
        $this->totalCount = $totalCount;
    }
}