<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** SCIMGroupRoleMapping - A mapping from a SCIM group to an organization role. Members of the group are assigned the role; the lowest-precedence match wins when a user belongs to multiple mapped groups. */
class SCIMGroupRoleMapping
{
    /**
     * String representing the object's type. Always "scim_group_role_mapping".
     *
     * @var \Clerk\Backend\Models\Components\SCIMGroupRoleMappingObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SCIMGroupRoleMappingObject')]
    public SCIMGroupRoleMappingObject $object;

    /**
     * Unique identifier for the SCIM group role mapping.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The ID of the SCIM directory this mapping belongs to.
     *
     * @var string $scimDirectoryId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_directory_id')]
    public string $scimDirectoryId;

    /**
     * The SCIM group ID from the identity provider.
     *
     * @var string $scimGroupId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_group_id')]
    public string $scimGroupId;

    /**
     * The display name of the SCIM group, as reported by the identity provider.
     *
     * @var string $scimGroupDisplayName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scim_group_display_name')]
    public string $scimGroupDisplayName;

    /**
     * Mapping precedence, starting at 1. Lower values take priority when a user belongs to multiple mapped groups.
     *
     * @var int $precedence
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('precedence')]
    public int $precedence;

    /**
     * Unix timestamp (milliseconds) of when the mapping was created.
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp (milliseconds) of when the mapping was last updated.
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\Role $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Role|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Role $role = null;

    /**
     * @param  \Clerk\Backend\Models\Components\SCIMGroupRoleMappingObject  $object
     * @param  string  $id
     * @param  string  $scimDirectoryId
     * @param  string  $scimGroupId
     * @param  string  $scimGroupDisplayName
     * @param  int  $precedence
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?\Clerk\Backend\Models\Components\Role  $role
     * @phpstan-pure
     */
    public function __construct(SCIMGroupRoleMappingObject $object, string $id, string $scimDirectoryId, string $scimGroupId, string $scimGroupDisplayName, int $precedence, int $createdAt, int $updatedAt, ?Role $role = null)
    {
        $this->object = $object;
        $this->id = $id;
        $this->scimDirectoryId = $scimDirectoryId;
        $this->scimGroupId = $scimGroupId;
        $this->scimGroupDisplayName = $scimGroupDisplayName;
        $this->precedence = $precedence;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->role = $role;
    }
}