<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


enum TicketVerificationSAMLAccountStrategy: string
{
    case Ticket = 'ticket';
}
