<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/**
 * UserDirectory - The most recently updated directory link. Use directories for all links.
 *
 * @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
class UserDirectory
{
    /**
     * The user's resource ID in this directory.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $directoryName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('directory_name')]
    public string $directoryName;

    /**
     *
     * @var string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    public string $provider;

    /**
     * The ID of the directory the user is provisioned from.
     *
     *
     *
     * @var string $directoryId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('directory_id')]
    public string $directoryId;

    /**
     * Whether the directory is currently enabled.
     *
     *
     *
     * @var bool $directoryEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('directory_enabled')]
    public bool $directoryEnabled;

    /**
     *
     * @var ?string $enterpriseConnectionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enterprise_connection_id')]
    public ?string $enterpriseConnectionId;

    /**
     * Omitted when groups were not loaded; an empty array means no group memberships.
     *
     * @var ?array<\Clerk\Backend\Models\Components\UserGroups> $groups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\UserGroups>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $groups = null;

    /**
     * The user's external ID as reported by the directory, if any.
     *
     *
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_id')]
    public ?string $externalId;

    /**
     * @param  string  $id
     * @param  string  $directoryName
     * @param  string  $provider
     * @param  string  $directoryId
     * @param  bool  $directoryEnabled
     * @param  ?string  $enterpriseConnectionId
     * @param  ?array<\Clerk\Backend\Models\Components\UserGroups>  $groups
     * @param  ?string  $externalId
     * @phpstan-pure
     */
    public function __construct(string $id, string $directoryName, string $provider, string $directoryId, bool $directoryEnabled, ?string $enterpriseConnectionId = null, ?array $groups = null, ?string $externalId = null)
    {
        $this->id = $id;
        $this->directoryName = $directoryName;
        $this->provider = $provider;
        $this->directoryId = $directoryId;
        $this->directoryEnabled = $directoryEnabled;
        $this->enterpriseConnectionId = $enterpriseConnectionId;
        $this->groups = $groups;
        $this->externalId = $externalId;
    }
}