<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class VerificationOTP
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationOtpVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationOtpVerificationStatus')]
    public VerificationOtpVerificationStatus $status;

    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationOtpVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationOtpVerificationStrategy')]
    public VerificationOtpVerificationStrategy $strategy;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationOtpVerificationObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationOtpVerificationObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationOtpVerificationObject $object = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public ?int $expireAt;

    /**
     * The delivery channel of the code (phone codes only).
     *
     * @var ?string $channel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $channel = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  \Clerk\Backend\Models\Components\VerificationOtpVerificationStatus  $status
     * @param  \Clerk\Backend\Models\Components\VerificationOtpVerificationStrategy  $strategy
     * @param  ?\Clerk\Backend\Models\Components\VerificationOtpVerificationObject  $object
     * @param  ?int  $attempts
     * @param  ?int  $expireAt
     * @param  ?string  $channel
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(VerificationOtpVerificationStatus $status, VerificationOtpVerificationStrategy $strategy, ?VerificationOtpVerificationObject $object = null, ?int $attempts = null, ?int $expireAt = null, ?string $channel = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->object = $object;
        $this->attempts = $attempts;
        $this->expireAt = $expireAt;
        $this->channel = $channel;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}