<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class VerificationOauth
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationOauthVerificationEnterpriseAccountStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationOauthVerificationEnterpriseAccountStatus')]
    public VerificationOauthVerificationEnterpriseAccountStatus $status;

    /**
     *
     * @var string $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    public string $strategy;

    /**
     *
     * @var int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public int $expireAt;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationOauthVerificationEnterpriseAccountObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationOauthVerificationEnterpriseAccountObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationOauthVerificationEnterpriseAccountObject $object = null;

    /**
     *
     * @var ?string $externalVerificationRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_verification_redirect_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalVerificationRedirectUrl = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationOauthErrorEnterpriseAccountClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationOauthErrorEnterpriseAccountClerkError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationOauthErrorEnterpriseAccountClerkError $error = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  \Clerk\Backend\Models\Components\VerificationOauthVerificationEnterpriseAccountStatus  $status
     * @param  string  $strategy
     * @param  int  $expireAt
     * @param  ?\Clerk\Backend\Models\Components\VerificationOauthVerificationEnterpriseAccountObject  $object
     * @param  ?string  $externalVerificationRedirectUrl
     * @param  ?int  $attempts
     * @param  ?\Clerk\Backend\Models\Components\VerificationOauthErrorEnterpriseAccountClerkError  $error
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(VerificationOauthVerificationEnterpriseAccountStatus $status, string $strategy, int $expireAt, ?VerificationOauthVerificationEnterpriseAccountObject $object = null, ?string $externalVerificationRedirectUrl = null, ?int $attempts = null, ?VerificationOauthErrorEnterpriseAccountClerkError $error = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->expireAt = $expireAt;
        $this->object = $object;
        $this->externalVerificationRedirectUrl = $externalVerificationRedirectUrl;
        $this->attempts = $attempts;
        $this->error = $error;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}