<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class VerificationSAMLVerificationEmailAddressSAML
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationSamlVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlVerificationStatus')]
    public VerificationSamlVerificationStatus $status;

    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationSamlVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlVerificationStrategy')]
    public VerificationSamlVerificationStrategy $strategy;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationSamlVerificationObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlVerificationObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationSamlVerificationObject $object = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?string $externalVerificationRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_verification_redirect_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalVerificationRedirectUrl = null;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationSamlErrorClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlErrorClerkError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationSamlErrorClerkError $error = null;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expireAt = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  \Clerk\Backend\Models\Components\VerificationSamlVerificationStatus  $status
     * @param  \Clerk\Backend\Models\Components\VerificationSamlVerificationStrategy  $strategy
     * @param  ?\Clerk\Backend\Models\Components\VerificationSamlVerificationObject  $object
     * @param  ?int  $attempts
     * @param  ?string  $externalVerificationRedirectUrl
     * @param  ?\Clerk\Backend\Models\Components\VerificationSamlErrorClerkError  $error
     * @param  ?int  $expireAt
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(VerificationSamlVerificationStatus $status, VerificationSamlVerificationStrategy $strategy, ?VerificationSamlVerificationObject $object = null, ?int $attempts = null, ?string $externalVerificationRedirectUrl = null, ?VerificationSamlErrorClerkError $error = null, ?int $expireAt = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->object = $object;
        $this->attempts = $attempts;
        $this->externalVerificationRedirectUrl = $externalVerificationRedirectUrl;
        $this->error = $error;
        $this->expireAt = $expireAt;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}