<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class VerificationSAMLVerificationSAML
{
    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountStatus')]
    public VerificationSamlVerificationEnterpriseAccountStatus $status;

    /**
     *
     * @var \Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountStrategy')]
    public VerificationSamlVerificationEnterpriseAccountStrategy $strategy;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountObject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationSamlVerificationEnterpriseAccountObject $object = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?string $externalVerificationRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_verification_redirect_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalVerificationRedirectUrl = null;

    /**
     *
     * @var ?\Clerk\Backend\Models\Components\VerificationSamlErrorEnterpriseAccountClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\VerificationSamlErrorEnterpriseAccountClerkError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationSamlErrorEnterpriseAccountClerkError $error = null;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expireAt = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  \Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountStatus  $status
     * @param  \Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountStrategy  $strategy
     * @param  ?\Clerk\Backend\Models\Components\VerificationSamlVerificationEnterpriseAccountObject  $object
     * @param  ?int  $attempts
     * @param  ?string  $externalVerificationRedirectUrl
     * @param  ?\Clerk\Backend\Models\Components\VerificationSamlErrorEnterpriseAccountClerkError  $error
     * @param  ?int  $expireAt
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(VerificationSamlVerificationEnterpriseAccountStatus $status, VerificationSamlVerificationEnterpriseAccountStrategy $strategy, ?VerificationSamlVerificationEnterpriseAccountObject $object = null, ?int $attempts = null, ?string $externalVerificationRedirectUrl = null, ?VerificationSamlErrorEnterpriseAccountClerkError $error = null, ?int $expireAt = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->object = $object;
        $this->attempts = $attempts;
        $this->externalVerificationRedirectUrl = $externalVerificationRedirectUrl;
        $this->error = $error;
        $this->expireAt = $expireAt;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}